- name: Install Pod | git update
  hosts: webservers encodeservers
  vars:
    ansible_ssh_user: pod
    ansible_ssh_private_key_file: '/home/pod/.ssh/id_rsa.pub'
  tasks:
    - name: git update
      git:
        clone: no
        update: yes
        force: yes
        repo: "{{depot}}"
        dest: "{{django_path}}"
    - name: django make migrations
      django_manage:
        command:  makemigrations
        app_path: "{{ django_path }}"
        virtualenv: "{{ venv_path }}/{{ venv }}"
    - name: django migrate
      django_manage:
        command: migrate
        app_path: "{{ django_path }}"
        virtualenv: "{{ venv_path }}/{{ venv }}"
    - name: django collectstatic
      django_manage:
        command: collectstatic
        app_path: "{{ django_path }}"
        virtualenv: "{{ venv_path }}/{{ venv }}"
    - name: restart uwsgi-pod
      service:
        name: uwsgi-pod
        state: restarted
      become: True



