- name: settings_local
  template:
    src: ../templates/settings_local.j2
    dest: "{{ django_path }}/pod/custom/settings_local.py"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0744

#- name: modif cas
#  copy:
#    src: ../files/views.py
#    dest: "{{venv_path}}/{{venv}}/lib/python3.5/site-packages/django_cas/views.py"
#    owner: "{{user}}"
#    group: "{{group}}"
#    mode: 0644
#  become: True
